// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: unique_id.proto

/*
Package go_micro_srv_unique_id is a generated protocol buffer package.

It is generated from these files:
	unique_id.proto

It has these top-level messages:
	UniqueIdRequest
	UniqueIdResponse
*/
package go_micro_srv_unique_id

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GenerateUniqueId service

type GenerateUniqueIdService interface {
	GenerateUniqueId(ctx context.Context, in *UniqueIdRequest, opts ...client.CallOption) (*UniqueIdResponse, error)
}

type generateUniqueIdService struct {
	c    client.Client
	name string
}

func NewGenerateUniqueIdService(name string, c client.Client) GenerateUniqueIdService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.unique_id"
	}
	return &generateUniqueIdService{
		c:    c,
		name: name,
	}
}

func (c *generateUniqueIdService) GenerateUniqueId(ctx context.Context, in *UniqueIdRequest, opts ...client.CallOption) (*UniqueIdResponse, error) {
	req := c.c.NewRequest(c.name, "GenerateUniqueId.GenerateUniqueId", in)
	out := new(UniqueIdResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GenerateUniqueId service

type GenerateUniqueIdHandler interface {
	GenerateUniqueId(context.Context, *UniqueIdRequest, *UniqueIdResponse) error
}

func RegisterGenerateUniqueIdHandler(s server.Server, hdlr GenerateUniqueIdHandler, opts ...server.HandlerOption) {
	type generateUniqueId interface {
		GenerateUniqueId(ctx context.Context, in *UniqueIdRequest, out *UniqueIdResponse) error
	}
	type GenerateUniqueId struct {
		generateUniqueId
	}
	h := &generateUniqueIdHandler{hdlr}
	s.Handle(s.NewHandler(&GenerateUniqueId{h}, opts...))
}

type generateUniqueIdHandler struct {
	GenerateUniqueIdHandler
}

func (h *generateUniqueIdHandler) GenerateUniqueId(ctx context.Context, in *UniqueIdRequest, out *UniqueIdResponse) error {
	return h.GenerateUniqueIdHandler.GenerateUniqueId(ctx, in, out)
}
