// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-06-22 14:53:27.5532595 +0800 CST m=+0.296829001

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "用户模块 Api文档",
        "title": "用户模块 Api文档",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "host": "192.168.0.167:9554",
    "basePath": "/dev/usr/v1",
    "paths": {
        "/address/add": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "address"
                ],
                "summary": "添加地址",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token令牌",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "地址ID",
                        "name": "address_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "姓名",
                        "name": "full_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "手机号",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "省份",
                        "name": "province",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "城市",
                        "name": "city",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "地区",
                        "name": "district",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "详细地址",
                        "name": "address",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\",\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/address/info": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "address"
                ],
                "summary": "获取地址信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token令牌",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "地址ID",
                        "name": "address_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\",\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/award/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "award"
                ],
                "summary": "获取中奖记录列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token令牌",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "总条数",
                        "name": "total_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "一页多少条数据",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\",\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/flow/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flow"
                ],
                "summary": "获取流水列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token令牌",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "总条数",
                        "name": "total_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "一页多少条数据",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\",\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/game/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "获取游戏记录列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token令牌",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "总条数",
                        "name": "total_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "一页多少条数据",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\",\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login/auth": {
            "post": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "登录授权",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商户ID",
                        "name": "merchant_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/notice/info": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notice"
                ],
                "summary": "获取公告信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token令牌",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "公告ID",
                        "name": "notice_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\",\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/notice/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notice"
                ],
                "summary": "获取公告列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token令牌",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "总条数",
                        "name": "total_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "一页多少条数据",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\",\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pay/express/create": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pay"
                ],
                "summary": "创建邮费订单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token令牌",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "兑换记录ID",
                        "name": "record_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "金额",
                        "name": "amount",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "交易类型 1|公众号 2|扫码",
                        "name": "trade_type",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\",\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pay/express/query": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pay"
                ],
                "summary": "邮费结果查询",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token令牌",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "交易ID",
                        "name": "recharge_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\",\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pay/recharge/create": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pay"
                ],
                "summary": "创建充值订单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token令牌",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "商户ID",
                        "name": "merchant_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "金额",
                        "name": "amount",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "交易类型 1|公众号 2|扫码",
                        "name": "trade_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "标签",
                        "name": "from_tag",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\",\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pay/recharge/query": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pay"
                ],
                "summary": "充值结果查询",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token令牌",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "交易ID",
                        "name": "recharge_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\",\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/room/award": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "room"
                ],
                "summary": "获取房间中奖列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token令牌",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "房间ID",
                        "name": "room_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "查询多少条数据",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\",\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/room/info": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "room"
                ],
                "summary": "获取房间信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token令牌",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "房间ID",
                        "name": "room_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\",\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/room/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "room"
                ],
                "summary": "获取房间列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token令牌",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "总条数",
                        "name": "total_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "一页多少条数据",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\",\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/suggest/add": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suggest"
                ],
                "summary": "添加意见",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token令牌",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "反馈内容",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "反馈类型 1|建议 2|投诉 3|其他",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "联系电话",
                        "name": "contact_tel",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\",\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/suggest/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suggest"
                ],
                "summary": "获取意见、投诉、列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token令牌",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "总条数",
                        "name": "total_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "一页多少条数据",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\",\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/test/info": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test"
                ],
                "summary": "测试专用",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Test",
                        "name": "test",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token令牌",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\",\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
